### ISSUE TITLE
`include ForkBreak::Breakpoints` sets a nil object

### ISSUE THREAD

**Issue by vemv** [forkbreak/fork_break#13]
Hi, I'm having trouble using the `include ForkBreak::Breakpoints` mechanism in any Rails model or plain class.

```ruby
class Foo
  
  include ForkBreak::Breakpoints
  
  def bar
    breakpoints << :test
  end
  
end
```

```
[8] pry(main)> Foo.new.bar
NoMethodError: undefined method `<<' for nil:NilClass
```

Using 0.1.3.

Any clue?

Cheers - Victor

**Comment by pedrocarrico** [comment]
Hi @vemv,

You can only access the breakpoints if you're inside a ForkBreak process.
Picking up on your example above:

```ruby
require 'fork_break'

class Foo
  include ForkBreak::Breakpoints

  def bar
    breakpoints << :test
  end
end

process = ForkBreak::Process.new { Foo.new.bar }

process.run_until(:test).wait # runs and stops at the :test breakpoint
process.finish # runs the process until finished
```
Check out the specs for another example.
Perhaps a better error message would help in this case or perhaps skip breakpoints if not in a ForkBreak process.

Thanks,

**Comment by vemv** [comment]
Ah, I see. Thanks!

Hmmm. I had imagined that by default breakpoints were always skipped if the current process is not a ForkBreak one. Else adding breakpoints would break production code, wouldn't they?

As I see it, one should be free to add breakpoints to controllers/models/etc, which would be a no-op in production. That way one could use the same exact code in prod and test envs...

Thoughts?

Cheers - Victor

**Comment by pedrocarrico** [comment]
Yes, that makes perfect sense!

I'll try to cook up the next version ASAP with that in mind.

Many thanks!

**Comment by vemv** [comment]
Thanks to you!

**Comment by vemv** [comment]
I played quite a lot with fork_break last night and was able to add breakpoints in production code without breaking anything. Feel free to merge!

**Comment by pedrocarrico** [comment]
Thank you for "playing" with fork_break, your comments matter a lot to us.

I'll rebase all PRs shortly and hopefully soon I'll push a new version to rubygems.

**Comment by remen** [comment]
Excellent! This was of course the intention all along!
