### ISSUE TITLE
Make BreakpointNotReachedError easier to debug

### ISSUE THREAD

**Issue by vemv** [forkbreak/fork_break#15]
Hi again!

I got one of these:

```
     ForkBreak::BreakpointNotReachedError:
       Never reached breakpoint :foo
```

This (rightfully) indicates that my code/test doesn't do what I expected to. But the error gives no debug information...

I'd include the return value of the run, for example:

```
     ForkBreak::BreakpointNotReachedError:
       Never reached breakpoint :foo. Process completed returning a value of 42
```

So when I see that 42, I can figure out what 'code path' did the process run take.

Sounds good?

Cheers - Victor

**Comment by vemv** [comment]
Similarly:

`ForkBreak::Process.new { ... }.run_until(:foo).finish` returns the following.

` #<ForkBreak::Process:0x007f9397b04b18 @debug=false, @fork=#<Fork pid=45711 alive=true>, @next_breakpoint=:forkbreak_end>`

I think there could be an additional `return_value` property there!

**Comment by vemv** [comment]
...the only thing being is that you cannot pass arbitrary Ruby objects between processes, i.e. I cannot get an ActiveRecord object from a fork. But calling `.to_s` and passing that string seems possible.

**Comment by pedrocarrico** [comment]
```quote
     ForkBreak::BreakpointNotReachedError:
       Never reached breakpoint :foo. Process completed returning a value of 42
```
I'd rather not clutter the error message and instead inspect the process to see what was the return value, what do you think?

```quote
...the only thing being is that you cannot pass arbitrary Ruby objects between processes, i.e. I cannot get an ActiveRecord object from a fork. But calling .to_s and passing that string seems possible.
```
I think that if the parent process has all the classes loaded fork allows marshalling the objects between processes and probably it will work.

Also, you'd have to always call wait to get the return value since `.finish` is a non-blocking call

Just submitted a PR, can you test it?

**Comment by vemv** [comment]
> I'd rather not clutter the error message and instead inspect the process to see what was the return value, what do you think?

Personally I'd prefer to put helpful info by default. One never actively expects to see `ForkBreak::BreakpointNotReachedError`, so debug info should be welcome when encountering these.

> I think that if the parent process has all the classes loaded fork allows marshalling the objects between processes and probably it will work.

Good reasoning! I'll give it a try.

> Also, you'd have to always call wait to get the return value since .finish is a non-blocking call

But I think, if ForkBreak::BreakpointNotReachedError is raised, it means something else was reached instead, and that the process finished already (no need to call `.wait`). So that 'something else' returned a value we can observe immediately. Correct?

**Comment by pedrocarrico** [comment]
> Personally I'd prefer to put helpful info by default. One never actively expects to see ForkBreak::BreakpointNotReachedError, so debug info should be welcome when encountering these.

Yeah, it works in the case of a simple object like a single String or Integer but in the case of a very complex object I'd rather not have all that information in an error message.

> But I think, if ForkBreak::BreakpointNotReachedError is raised, it means something else was reached instead, and that the process finished already (no need to call .wait). So that 'something else' returned a value we can observe immediately. Correct?

Correct, the implementation in #17 reflects that also.

**Comment by vemv** [comment]
Alright! Personally I'd put the info, but it doesn't matter a lot. It will be a few keystrokes away now :)
