### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by pedrocarrico** [forkbreak/fork_break#9]
Hi @remen ,

Can you please enable the build of this repo in https://travis-ci.org?

Or perhaps you could create a new open-source organization and that way we could both retain ownership of this project and control these things?

Thanks,

**Comment by remen** [comment]
Done. Moved the repository to https://github.com/forkbreak/fork_break (underscores are not allowed in github orgs)

**Comment by pedrocarrico** [comment]
:+1:
